"""add login_failures table

Revision ID: d779ef7826f7
Revises: 75cc10f0b926
Create Date: 2026-10-10 11:27:08.550012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd779ef7826f7'
down_revision: Union[str, Sequence[str], None] = '75cc10f0b926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_failures_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_failures_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_failures_ip'), ['ip'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_failures_ip'))
        batch_op.drop_index(batch_op.f('ix_login_failures_email'))
        batch_op.drop_index(batch_op.f('ix_login_failures_created_at'))

    op.drop_table('login_failures')
    # ### end Alembic commands ###
